"""E09 Trend engine package (multi-scale trend: MICRO/SHORT/INTER/MACRO
with TrendStack + full Wilder ADX + Newey-West slope + Mann-Kendall +
Anis-Lloyd Hurst)."""
from apex.engines.e09_trend.engine import (  # noqa: F401
    ALIGNMENTS,
    ANALYST_VERSION,
    CONTRACT_VERSION,
    ENGINE,
    EPS,
    E09_DEFAULTS,
    E09TrendEngine,
    EVENT_CATALOG,
    SCALES,
    STATE_FATES,
    W_STACK_CORRECTED,
    TrendEngine,
    TrendScale,
    alignment_of,
    anis_lloyd_expected_rs,
    compute_adx_wilder,
    compute_pos_scale,
    compute_seq_score,
    compute_trend_quality,
    divergence_exhaustion_check,
    get_params,
    hurst_rs_anis_lloyd_corrected,
    mann_kendall_with_tie_correction,
    observation_to_bar,
    ols_slope_newey_west,
    quality_label,
    run_engine,
    trend_direction_and_strength,
    validate_bar,
    wilder_rma,
    wilson_ci,
)
