"""E12 — Temporal Context Engine package (v4.0.0).

E12 owns the canonical UTC activity-window registry (§3.5) and is the sole
runtime source for primary UTC activity-window routing; consumers: E07
(utc_activity_window permission via ``E12TemporalProvider``), Context Fabric
(§5 SL-1), Telegram reporting (Chapter 6).  E12 outputs are Context — never
signals or permissions.
"""

from apex.engines.e12_temporal.engine import (  # noqa: F401
    ANALYST_VERSION,
    CALENDAR_CONFIG_VERSION,
    CONTRACT_LABEL,
    CONTRACT_VERSION,
    DAY_TYPES,
    E07_CONTRACT_LABEL,
    E12_DEFAULTS,
    ENGINE,
    ENGINE_ID,
    EPS,
    EVENT_CATALOG,
    FATE_VALUES,
    FOURIER_K_DEFAULT,
    N_BINS_DEFAULT,
    OVERLAP_LABEL,
    OVERLAP_WINDOW,
    PHASES,
    PRIMARY_WINDOWS,
    QUALITY_TAGS,
    STATE_REQUIRED,
    TOD_STATE_REQUIRED,
    UTC_ACTIVITY_WINDOWS,
    UTC_CORE_WINDOWS,
    WILSON_Z,
    E12TemporalEngine,
    E12TemporalProvider,
    EngineParams,
    TemporalContextEngine,
    TemporalWindowEngineStream,
    catalog_events,
    chi2_sf,
    compute_temporal_profile,
    condition_key,
    conditional_rate,
    day_type,
    deseasonalize,
    deterministic_replay_check,
    fff_seasonal,
    fourier_smooth_factors,
    get_params,
    hour_float,
    intraday_momentum_beta,
    is_core_window,
    kruskal_wallis,
    load_v3_temporal_payload,
    make_snapshot_id,
    no_future_leak_check,
    observation_to_candle,
    param_hash,
    profile_stability,
    range_z,
    returns_by_tod_from_candles,
    rollover_is_active,
    run_engine,
    seasonal_profile_available,
    serialize_state,
    spearman_rho,
    test_temporal_window_difference,
    tod_bin,
    ts_from_ms,
    utc_activity_window_of,
    validate_state_schema,
    vol_ratio,
    window_progress,
    wilson_ci,
    winsorize,
    y_range,
    y_vol,
)

__all__ = [
    "ANALYST_VERSION", "CALENDAR_CONFIG_VERSION", "CONTRACT_LABEL",
    "CONTRACT_VERSION", "DAY_TYPES", "E07_CONTRACT_LABEL", "E12_DEFAULTS",
    "E12TemporalEngine", "E12TemporalProvider", "ENGINE", "ENGINE_ID", "EPS",
    "EVENT_CATALOG", "EngineParams", "FATE_VALUES", "FOURIER_K_DEFAULT",
    "N_BINS_DEFAULT", "OVERLAP_LABEL", "OVERLAP_WINDOW", "PHASES",
    "PRIMARY_WINDOWS", "QUALITY_TAGS", "STATE_REQUIRED",
    "TOD_STATE_REQUIRED", "TemporalContextEngine", "TemporalWindowEngineStream",
    "UTC_ACTIVITY_WINDOWS", "UTC_CORE_WINDOWS", "WILSON_Z", "catalog_events",
    "chi2_sf", "compute_temporal_profile", "condition_key", "conditional_rate",
    "day_type", "deseasonalize", "deterministic_replay_check", "fff_seasonal",
    "fourier_smooth_factors", "get_params", "hour_float",
    "intraday_momentum_beta", "is_core_window", "kruskal_wallis",
    "load_v3_temporal_payload", "make_snapshot_id", "no_future_leak_check",
    "observation_to_candle", "param_hash", "profile_stability", "range_z",
    "returns_by_tod_from_candles", "rollover_is_active", "run_engine",
    "seasonal_profile_available", "serialize_state", "spearman_rho",
    "test_temporal_window_difference", "tod_bin", "ts_from_ms",
    "utc_activity_window_of", "validate_state_schema", "vol_ratio",
    "window_progress", "wilson_ci", "winsorize", "y_range", "y_vol",
]
