"""E10 Momentum engine package (MomentumState v4.0.0; smoothed velocity/
acceleration, MomentumZ, MvZ participation, Wilder-RMA RSI / ROC /
Stochastic / full MACD, symmetric Impulse-Exhaustion, four divergence kinds
+ CONVERGENCE + NONE via OLS β and confirmed both-pivot methods)."""
from apex.engines.e10_momentum.engine import (  # noqa: F401
    ANALYST_VERSION,
    CONTRACT_LABEL,
    CONTRACT_VERSION,
    DIVERGENCE_KINDS,
    DIVERGENCE_METHODS,
    E10_DEFAULTS,
    E10MomentumEngine,
    EMAState,
    ENGINE,
    EPS,
    EVENT_CATALOG,
    FATES,
    INTERVALS,
    KIND_TO_EVENT,
    MOMENTUM_STATE_REQUIRED,
    Q_TAGS,
    REFERENCE_MODES,
    TF_SECONDS,
    Candle,
    DivergenceEvent,
    EngineParams,
    MomentumEngine,
    Pivot,
    calibration_report,
    candle_from_bar,
    catalog_events,
    classify_pivot_pair,
    deterministic_replay_check,
    divergence_mag_ols,
    divergence_mag_pivot,
    divergence_success,
    e10_snapshot_id,
    get_params,
    impulse_exhaustion_flags,
    load_v3_adapter,
    log_return,
    macd_state,
    momentum_state_projection,
    momentum_z,
    no_future_leak_check,
    observation_to_bar,
    ols_slope,
    param_hash,
    pearson_corr,
    redundancy_report,
    roc,
    rsi_series,
    run_engine,
    stochastic_kd,
    validate_state_schema,
    volume_features,
    wilson_ci,
)
