"""APEX_GEN5 Evidence Fabric package (Ch.8 §8.0, SL-1/SL-14; CP-6).

Read-only assembly layer: engines publish events, they never mutate a fabric
in place (Ch.8 §8.0). Evidence enters/leaves a fabric ONLY through the unified
lifecycle state machine SL-14 (crosswalk in ``apex.fabric.evidence``).
"""

from apex.fabric.evidence import (  # noqa: F401
    ENGINE_GROUPS,
    EVIDENCE_LIFECYCLE_STATES,
    ENGINE_LIFECYCLE_STATES,
    EXPIRY_TF_MULTIPLE,
    FABRIC_ADMIT_STATE,
    SL14_CROSSWALK,
    TERMINAL_STATES,
    EvidenceFabric,
    FabricEvidenceRef,
    advance_lifecycle,
    engine_group_of,
    evidence_freshness,
    expiry_age_bars,
    fabric_from_events,
    is_forward,
    lifecycle_of,
    make_fabric_id,
    make_hash,
)
from apex.fabric.context import (  # noqa: F401
    BAND_ADMISSIBLE,
    BAND_CONFIRMATORY,
    COMPONENT_ENGINE,
    CONTEXT_BAND_GRID,
    CONTEXT_COMPONENTS_12,
    CombinerInputs,
    ContextRecord,
    DEFAULT_COMBINER_WEIGHTS,
    build_context,
    ENGINE_COMPONENT,
    MTF_STATE_SCORES,
    REDUNDANCY_HALVE_FACTOR,
    apply_redundancy,
    band_of,
    conflict_multiplier,
    context_bands,
    context_confidence,
    context_decay_per_bar,
    context_weights,
    data_trust_floor,
    evidence_agreement,
    evidence_decay_per_bar,
    freshness_factor,
    mtf_agreement,
    normalized_context_weights,
    propagation_band,
    propagation_confirmatory_threshold,
    q_min_setup,
    q_min_tf,
    raw_setup_score,
    redundancy_penalty_value,
    redundancy_rho,
    redundancy_rho_threshold,
    setup_score,
    solvency_check,
)
from apex.fabric.conflict import (  # noqa: F401
    CONFLICT_OUTPUTS,
    CONSENSUS,
    GATE3_CONFLICT_THRESHOLD,
    GATE4_REDUNDANCY_THRESHOLD,
    HARD_CONFLICT,
    HARD_DISAGREEMENT,
    INSUFFICIENT_EVIDENCE,
    InvariantViolation,
    MATERIAL_CONFLICT,
    MATERIAL_DISAGREEMENT,
    SMTRecord,
    SEVEN_INVARIANTS,
    CorrelationRecord,
    ConflictRecord,
    DivergenceRecord,
    assert_no_reversion_semantics,
    assert_permission_monotone,
    correlation_exposure,
    disagreement_of,
    gate_thresholds,
    monotone_ok,
    penalties,
    quality_asymmetry_of,
    resolve,
    stale_fraction_of,
)
